[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyuptimekuma"
dynamic = ["version"]
description = "Simple Python wrapper for Uptime Kuma"
readme = "README.md"
license = "MIT"
requires-python = ">=3.8.0"
authors = [
    { name = "Jayakorn Karikan", email = "jayakornk@gmail.com" },
]
keywords = [
    "pyuptimekuma",
    "setuptools",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "aiohttp>=3.8.1,<4.0",
    "prometheus-client>=0.14.1",
]

[project.optional-dependencies]
dev = [
    "black==22.3.0",
    "isort==5.10.1",
]

[project.urls]
Homepage = "https://github.com/jayakornk/pyuptimekuma"

[tool.hatch.version]
path = "pyuptimekuma/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/pyuptimekuma",
]

